import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider } from "../lib/auth-context";
import NavBar from "./components/NavBar";
import { ProductStoreProvider } from "../lib/stores/product-store";
import { SellStoreProvider } from "../lib/stores/sell-store";
import { ToastProvider } from "../lib/toast-context";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthProvider>
          <ToastProvider>
            <ProductStoreProvider>
              <SellStoreProvider>
                <NavBar />
                <div className="container">{children}</div>
                <Footer />
              </SellStoreProvider>
            </ProductStoreProvider>
          </ToastProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
